stages:
  - deploy

deploy:
  stage: deploy
  image: alpine:3
  script:
    - apk add curl
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=dev "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'
  environment: production