name: CI

on:
  push:
    branches:
    - main
  pull_request: ~

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - uses: php-actions/phpunit@v3
      with:
        php_extensions: xdebug
        coverage_cobertura: "coverage.xml"
      env:
        XDEBUG_MODE: coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - uses: thenabeel/action-phpcs@v8
      with:
        phpcs_path: php ./vendor/bin/phpcs
        standard: phpcs.xml
